In [1]:
import numpy as np

In [2]:
x = [1, 2, 3, 4]
arr = np.array(x)
arr

array([1, 2, 3, 4])

In [3]:
y = np.random.randint(1, 2000, 5)
y

array([ 934,  624, 1126,  486, 1990])

In [4]:
x = np.random.rand(50)
x

array([0.11083492, 0.05138405, 0.17556754, 0.36669039, 0.05003708,
       0.4215175 , 0.03649002, 0.71210741, 0.48318145, 0.5330994 ,
       0.30658249, 0.22991893, 0.46404185, 0.60237076, 0.11546551,
       0.6757863 , 0.09778384, 0.12812527, 0.70315779, 0.64401349,
       0.49990561, 0.46372161, 0.80490214, 0.61226114, 0.44778642,
       0.5194004 , 0.36950792, 0.3429985 , 0.74300813, 0.03925533,
       0.78776694, 0.0681258 , 0.72235424, 0.73737622, 0.09807932,
       0.47644853, 0.88321399, 0.48940689, 0.9240161 , 0.03303685,
       0.87970832, 0.16567158, 0.21927904, 0.78997382, 0.24534402,
       0.19305774, 0.87730349, 0.93616815, 0.13932542, 0.63201432])

In [5]:
np.reshape(x, (10, 5))

array([[0.11083492, 0.05138405, 0.17556754, 0.36669039, 0.05003708],
       [0.4215175 , 0.03649002, 0.71210741, 0.48318145, 0.5330994 ],
       [0.30658249, 0.22991893, 0.46404185, 0.60237076, 0.11546551],
       [0.6757863 , 0.09778384, 0.12812527, 0.70315779, 0.64401349],
       [0.49990561, 0.46372161, 0.80490214, 0.61226114, 0.44778642],
       [0.5194004 , 0.36950792, 0.3429985 , 0.74300813, 0.03925533],
       [0.78776694, 0.0681258 , 0.72235424, 0.73737622, 0.09807932],
       [0.47644853, 0.88321399, 0.48940689, 0.9240161 , 0.03303685],
       [0.87970832, 0.16567158, 0.21927904, 0.78997382, 0.24534402],
       [0.19305774, 0.87730349, 0.93616815, 0.13932542, 0.63201432]])

In [1]:
import cv2
img = cv2.imread("C:\\College\\College\\Python\\Computer Vision\\Photos\\G-1.jpg")
img2 = cv2.imread("C:\\College\\College\\Python\\Computer Vision\\Photos\\G-2.jpg")
img3 = cv2.imread("C:\\College\\College\\Python\\Computer Vision\\Photos\\G-3.jpg")

l = [img, img2, img3]
cv2.imshow('Image-1', img)
cv2.imshow('Image-2', img2)
cv2.imshow('Image-3', img3)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [2]:
img = cv2.imread("C:\\College\\College\\Python\\Computer Vision\\Photos\\G-1.jpg", 0)
cv2.imshow('Image', img)
cv2.waitKey(0)

-1

In [5]:
flip = cv2.flip(img, -1)
cv2.imshow('Flip', flip)
key = cv2.waitKey(0)

if(key == ord('q')):
    cv2.destroyAllWindows()
elif(key == ord('s')):
    cv2.imwrite('flip.jpg', flip)
    cv2.destroyAllWindows()

In [4]:
for i in range(len(l)):
    flip = cv2.flip(l[i], -1)
    cv2.imshow(f'Flip{i}', flip)
    key = cv2.waitKey(0)
    if(key == ord('q')):
        cv2.destroyAllWindows()
    elif(key == ord('s')):
        cv2.imwrite(f'flip-{i}.jpg', flip)
        cv2.destroyAllWindows()